export const leadsData = [
  {
    name: "PLASTICOS ROCA S.A.C.",
    logo: "https://expoplastperu.com/guia/images/anuncios-empresas/5eeff36021799-logo.png",
    data: [
      "+51 1 7479497",
      "+51 999335633",
      "ventas@plasticosroca.com.pe",
      "http://www.plasticosroca.com.pe",
    ],
    category: "envases-plasticos",
    tiers: 1,
    teus: 3,
  },
  {
    name: "TECNIPACK S.A.C.",
    logo: "https://expoplastperu.com/guia/images/anuncios-empresas/5f2378fec591a-logo.png",
    data: [
      "+51 1 3486647  +51 1 3483749",
      "ventas@tecnipacksac.com",
      "http://www.tecnipacksac.com",
    ],
    category: "envases-plasticos",
    tiers: 2,
    teus: 9,
  },
  {
    name: "EUROPLAST S.A.C.",
    logo: "https://expoplastperu.com/guia/images/anuncios-empresas/5ef0257c57fed-logo.png",
    data: [
      "+51 1 3480886",
      "WhatsApp +51 998369875",
      "info@europlast.pe",
      "http://www.europlast.pe",
    ],
    category: "envases-plasticos",
    tiers: 1,
    teus: 4,
  },
  {
    name: "CORSUN S.A.C.",
    logo: "https://expoplastperu.com/guia/images/anuncios-empresas/5f1a725f71a8f-logo.png",
    data: [
      "+51 1 4404191",
      "comercial@corsun.com.pe",
      "http://www.corsun.com.pe",
    ],
    category: "envases-plasticos",
    tiers: 2,
    teus: 3,
  },
  {
    name: "MELAFORM S.A.C.",
    logo: "https://expoplastperu.com/guia/images/anuncios-empresas/5ef03adde3060-logo.png",
    data: [
      "+51 1 4590026",
      "ventasnacionales@melaform.com.pe",
      "http://www.melaform.com.pe",
    ],
    category: "envases-plasticos",
    tiers: 2,
    teus: 2,
  },
  {
    name: "VIGOFLEX PACKAGING ",
    logo: "https://expoplastperu.com/guia/images/anuncios-empresas/62aa08310a10f-logo.png",
    data: [
      "(Perú) +51 1 480 0227 / (Chile) +56 2 2904 9925",
      "+51 912 267 183",
      "info@vigoflex.com",
      "http://www.vigoflex.com",
    ],
    category: "envases-plasticos",
    tiers: 0,
    teus: 5,
  },
];
